# Generated by Django 5.0.7 on 2024-07-18 21:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoiceentry_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='grand_total_taxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
