# Generated by Django 5.0.7 on 2024-07-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoiceentry_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceentrylineproduct',
            old_name='amount',
            new_name='amount_before_tax',
        ),
    ]
