# Generated by Django 5.0.7 on 2024-07-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoiceentrylineproduct_amount_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentrylineproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
