# Generated by Django 5.0.7 on 2024-07-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_forms.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_forms.store'),
            preserve_default=False,
        ),
    ]
