# Generated by Django 5.0.7 on 2024-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_forms', '0002_product_store_service_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
