# Generated by Django 5.0.7 on 2024-07-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COA', '0004_coa'),
        ('Journal_Entries', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COA.coa')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.journalentries')),
            ],
        ),
    ]
