# Generated by Django 5.0.7 on 2024-07-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0007_alter_journalentrylines_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentrylines',
            options={},
        ),
        migrations.RemoveField(
            model_name='journalentrylines',
            name='description',
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('vendor', 'Vendor'), ('customer', 'Customer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='account',
            field=models.CharField(max_length=100),
        ),
    ]
