# Generated by Django 5.0.7 on 2024-07-16 20:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COA', '0004_coa'),
        ('Journal_Entries', '0009_remove_journalentrylines_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('journal_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('posted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.project')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('journal_entry_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COA.coa')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.journalentries')),
            ],
        ),
    ]
