# Generated by Django 5.0.7 on 2024-07-17 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0011_remove_journalentries_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentrylines',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Journal_Entries.journalentries'),
        ),
    ]
