# Generated by Django 5.0.7 on 2024-07-17 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0013_journalentrylines_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylines',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.project'),
        ),
    ]
