# Generated by Django 5.0.7 on 2024-07-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0014_journalentrylines_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentries',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='project',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='vendor',
        ),
    ]
