# Generated by Django 5.0.7 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0015_remove_journalentries_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
