# Generated by Django 5.0.7 on 2024-07-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0016_journalentrylines_name_selection_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentrylines',
            name='name_selection_id',
        ),
    ]
