# Generated by Django 5.0.7 on 2024-07-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0017_remove_journalentrylines_name_selection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentrylines',
            name='name_selection_type',
        ),
    ]
