# Generated by Django 5.0.7 on 2024-07-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0019_alter_project_id'),
        ('general_forms', '0002_product_store_service_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_forms.store'),
            preserve_default=False,
        ),
    ]
