from django.db import models

class AccountTypes(models.Model):
    AccountType_CHOICES = [
        ('Accounts Receivable', 'Accounts Receivable'),
        ('Current Assets', 'Current Assets'),
        ('Bank', 'Bank'),
        ('Property, Plant and equipment', 'Property, Plant and equipment'),
        ('Long-Term Assets', 'Long-Term Assets'),
        ('Accounts Payable (A/P)', 'Accounts Payable (A/P)'),
        ('Credit Card', 'Credit Card'),
        ('Other Current Liabilities', 'Other Current Liabilities'),
        ('Long Term Liabilities', 'Long Term Liabilities'),
        ('Equity', 'Equity'),
        ('Income', 'Income'),
        ('Other Income', 'Other Income'),
        ('Cost of Goods Sold', 'Cost of Goods Sold'),
        ('Expenses', 'Expenses'),
        ('Other Expenses', 'Other Expenses'),
    ]
    
    AccountType = models.CharField(max_length=50, choices=AccountType_CHOICES, primary_key=True)

    def __str__(self):
        return self.AccountType


class DetailTypes(models.Model):
    AccountType_CHOICES = [
        ('Accounts Receivable', 'Accounts Receivable'),
        ('Current Assets', 'Current Assets'),
        ('Bank', 'Bank'),
        ('Property, Plant and equipment', 'Property, Plant and equipment'),
        ('Long-Term Assets', 'Long-Term Assets'),
        ('Accounts Payable (A/P)', 'Accounts Payable (A/P)'),
        ('Credit Card', 'Credit Card'),
        ('Other Current Liabilities', 'Other Current Liabilities'),
        ('Long Term Liabilities', 'Long Term Liabilities'),
        ('Equity', 'Equity'),
        ('Income', 'Income'),
        ('Other Income', 'Other Income'),
        ('Cost of Goods Sold', 'Cost of Goods Sold'),
        ('Expenses', 'Expenses'),
        ('Other Expenses', 'Other Expenses'),
    ]
    
    DetailType_CHOICES = [
        ('Accounts Receivable', 'Accounts Receivable'),
        ('Allowance for bad debts', 'Allowance for bad debts'),
        ('Development Cost', 'Development Cost'),
        ('Employee Cash Advances', 'Employee Cash Advances'),
        ('Inventory', 'Inventory'),
        ('Investments - Other', 'Investments - Other'),
        ('Loans to Officers', 'Loans to Officers'),
        ('Loans to Others', 'Loans to Others'),
        ('Loans to Shareholders', 'Loans to Shareholders'),
        ('Other current assets', 'Other current assets'),
        ('Prepaid Expenses', 'Prepaid Expenses'),
        ('Retainage', 'Retainage'),
        ('Undeposited Funds', 'Undeposited Funds'),
        ('Cash on hand', 'Cash on hand'),
        ('Chequing', 'Chequing'),
        ('Money Market', 'Money Market'),
        ('Rents Held in Trust', 'Rents Held in Trust'),
        ('Savings', 'Savings'),
        ('Trust Account', 'Trust Account'),
        ('Accumulated Amortization', 'Accumulated Amortization'),
        ('Accumulated Depreciation', 'Accumulated Depreciation'),
        ('Accumulated depletion', 'Accumulated depletion'),
        ('Buildings', 'Buildings'),
        ('Depletable Assets', 'Depletable Assets'),
        ('Furniture and Fixtures', 'Furniture and Fixtures'),
        ('Leasehold Improvements', 'Leasehold Improvements'),
        ('Machinery and equipment', 'Machinery and equipment'),
        ('Other fixed assets', 'Other fixed assets'),
        ('Vehicles', 'Vehicles'),
        ('Accumulated Amortization of Other Assets', 'Accumulated Amortization of Other Assets'),
        ('Available-for-sale financial assets', 'Available-for-sale financial assets'),
        ('Deferred tax', 'Deferred tax'),
        ('Intangible Assets', 'Intangible Assets'),
        ('Investments', 'Investments'),
        ('Lease Buyout', 'Lease Buyout'),
        ('Licenses', 'Licenses'),
        ('Organizational Costs', 'Organizational Costs'),
        ('Other Long-term Assets', 'Other Long-term Assets'),
        ('Other intangible assets', 'Other intangible assets'),
        ('Prepayments and accrued income', 'Prepayments and accrued income'),
        ('Security Deposits', 'Security Deposits'),
        ('Accounts Payable (A/P)', 'Accounts Payable (A/P)'),
        ('Credit Card', 'Credit Card'),
        ('Current Liabilities', 'Current Liabilities'),
        ('Current Tax Liability', 'Current Tax Liability'),
        ('Current portion of employee benefits obligations', 'Current portion of employee benefits obligations'),
        ('Current portion of obligation under finance leases', 'Current portion of obligation under finance leases'),
        ('Insurance Payable', 'Insurance Payable'),
        ('Interest Payables', 'Interest Payables'),
        ('Line of Credit', 'Line of Credit'),
        ('Loan Payable', 'Loan Payable'),
        ('Payroll Clearing', 'Payroll Clearing'),
        ('Payroll liabilities', 'Payroll liabilities'),
        ('Prepaid Expenses Payable', 'Prepaid Expenses Payable'),
        ('Provision for warranty obligations', 'Provision for warranty obligations'),
        ('Rents in trust – Liability', 'Rents in trust – Liability'),
        ('Short term borrowings from related parties', 'Short term borrowings from related parties'),
        ('Trust Accounts – Liabilities', 'Trust Accounts – Liabilities'),
        ('Accruals and Deferred Income', 'Accruals and Deferred Income'),
        ('Bank loans', 'Bank loans'),
        ('Long term borrowings', 'Long term borrowings'),
        ('Long term employee benefit obligations', 'Long term employee benefit obligations'),
        ('Other Long-Term Liabilities', 'Other Long-Term Liabilities'),
        ('Shareholder Notes Payable', 'Shareholder Notes Payable'),
        ('Accumulated adjustment', 'Accumulated adjustment'),
        ('Common Stock', 'Common Stock'),
        ('Owner\'s Equity', 'Owner\'s Equity'),
        ('Paid-in capital or surplus', 'Paid-in capital or surplus'),
        ('Partner Contributions', 'Partner Contributions'),
        ('Partner Distributions', 'Partner Distributions'),
        ('Partner\'s Equity', 'Partner\'s Equity'),
        ('Preferred Stock', 'Preferred Stock'),
        ('Retained Earnings', 'Retained Earnings'),
        ('Share capital', 'Share capital'),
        ('Treasury Shares', 'Treasury Shares'),
        ('Discounts/Refunds given', 'Discounts/Refunds given'),
        ('Non-Profit Income', 'Non-Profit Income'),
        ('Other Primary Income', 'Other Primary Income'),
        ('Sales of Product Income', 'Sales of Product Income'),
        ('Service/Fee Income', 'Service/Fee Income'),
        ('Unapplied Cash Payment income', 'Unapplied Cash Payment income'),
        ('Dividend Income', 'Dividend Income'),
        ('Gain/loss on sale of fixed assets', 'Gain/loss on sale of fixed assets'),
        ('Gain/loss on sale of investments', 'Gain/loss on sale of investments'),
        ('Income', 'Income'),
        ('Interest earned', 'Interest earned'),
        ('Other Investment Income', 'Other Investment Income'),
        ('Tax-Exempt Interest', 'Tax-Exempt Interest'),
        ('Cost of Goods Sold', 'Cost of Goods Sold'),
        ('Cost of Labor - COS', 'Cost of Labor - COS'),
        ('Equipment rental - COS', 'Equipment rental - COS'),
        ('Other costs of service - COS', 'Other costs of service - COS'),
        ('Shipping, Freight and Delivery – COS', 'Shipping, Freight and Delivery – COS'),
        ('Supplies and materials - COS', 'Supplies and materials - COS'),
        ('Advertising/Promotional', 'Advertising/Promotional'),
        ('Auto', 'Auto'),
        ('Bad debts', 'Bad debts'),
        ('Bank charges', 'Bank charges'),
        ('Charitable Contributions', 'Charitable Contributions'),
        ('Cost of Labor', 'Cost of Labor'),
        ('Distribution costs', 'Distribution costs'),
        ('Dues and Subscriptions', 'Dues and Subscriptions'),
        ('Entertainment', 'Entertainment'),
        ('Equipment rental', 'Equipment rental'),
        ('Insurance', 'Insurance'),
        ('Interest paid', 'Interest paid'),
        ('Legal and professional fees', 'Legal and professional fees'),
        ('Meals and entertainment', 'Meals and entertainment'),
        ('Office/General Administrative Expenses', 'Office/General Administrative Expenses'),
        ('Other miscellaneous Service Cost', 'Other miscellaneous Service Cost'),
        ('Payroll Expenses', 'Payroll Expenses'),
        ('Promotional Meals', 'Promotional Meals'),
        ('Rent or lease of Buildings', 'Rent or lease of Buildings'),
        ('Repair and maintenance', 'Repair and maintenance'),
        ('Shipping, Freight and Delivery', 'Shipping, Freight and Delivery'),
        ('Supplies', 'Supplies'),
        ('Taxes paid', 'Taxes paid'),
        ('Travel', 'Travel'),
        ('Travel meals', 'Travel meals'),
        ('Unapplied Cash Bill Payment Expenses', 'Unapplied Cash Bill Payment Expenses'),
        ('Utilities', 'Utilities'),
        ('Amortization', 'Amortization'),
        ('Depreciation', 'Depreciation'),
        ('Exchange Gain or Loss', 'Exchange Gain or Loss'),
        ('Other Miscellaneous Expenses', 'Other Miscellaneous Expenses'),
        ('Penalties and settlements', 'Penalties and settlements'),
    ]
    
    AccountType = models.CharField(max_length=50, choices=AccountType_CHOICES, db_index=True)
    DetailType = models.CharField(max_length=100, choices=DetailType_CHOICES)
    
    class Meta:
        unique_together = ('AccountType', 'DetailType')
    
    def __str__(self):
        return f'{self.AccountType} - {self.DetailType}'


class COA(models.Model):
    ACCOUNT_TYPES = [
        ('Accounts Receivable (A/R)', 'Accounts Receivable (A/R)'),
        ('Current Assets', 'Current Assets'),
        ('Bank', 'Bank'),
        ('Property, Plant and equipment', 'Property, Plant and equipment'),
        ('Long-Term Assets', 'Long-Term Assets'),
        ('Accounts Payable (A/P)', 'Accounts Payable (A/P)'),
        ('Credit Card', 'Credit Card'),
        ('Other Current Liabilities', 'Other Current Liabilities'),
        ('Long Term Liabilities', 'Long Term Liabilities'),
        ('Equity', 'Equity'),
        ('Income', 'Income'),
        ('Other Income', 'Other Income'),
        ('Cost of Goods Sold', 'Cost of Goods Sold'),
        ('Expenses', 'Expenses'),
        ('Other Expenses', 'Other Expenses'),
    ]

    DETAIL_TYPES = {
        'Accounts Receivable (A/R)': [
            ('Accounts Receivable', 'Accounts Receivable'),
        ],
        'Current Assets': [
            ('Allowance for bad debts', 'Allowance for bad debts'),
            ('Development Costs', 'Development Costs'),
            ('Employee Cash Advances', 'Employee Cash Advances'),
            ('Inventory', 'Inventory'),
            ('Investments - Other', 'Investments - Other'),
            ('Loans To Officers', 'Loans To Officers'),
            ('Loans to Others', 'Loans to Others'),
            ('Loans to Shareholders', 'Loans to Shareholders'),
            ('Other current assets', 'Other current assets'),
            ('Prepaid Expenses', 'Prepaid Expenses'),
            ('Retainage', 'Retainage'),
            ('Undeposited Funds', 'Undeposited Funds'),
        ],
        'Bank': [
            ('Cash on hand', 'Cash on hand'),
            ('Chequing', 'Chequing'),
            ('Money Market', 'Money Market'),
            ('Rents Held in Trust', 'Rents Held in Trust'),
            ('Savings', 'Savings'),
            ('Trust Account', 'Trust Account'),
        ],
        'Property, Plant and equipment': [
            ('Accumulated Amortization', 'Accumulated Amortization'),
            ('Accumulated Depreciation', 'Accumulated Depreciation'),
            ('Accumulated depletion', 'Accumulated depletion'),
            ('Buildings', 'Buildings'),
            ('Depletable Assets', 'Depletable Assets'),
            ('Furniture and Fixtures', 'Furniture and Fixtures'),
            ('Leasehold Improvements', 'Leasehold Improvements'),
            ('Machinery and equipment', 'Machinery and equipment'),
            ('Other fixed assets', 'Other fixed assets'),
            ('Vehicles', 'Vehicles'),
        ],
        'Long-Term Assets': [
            ('Accumulated Amortization of Other Assets', 'Accumulated Amortization of Other Assets'),
            ('Available-for-sale financial assets', 'Available-for-sale financial assets'),
            ('Deferred tax', 'Deferred tax'),
            ('Intangible Assets', 'Intangible Assets'),
            ('Investments', 'Investments'),
            ('Lease Buyout', 'Lease Buyout'),
            ('Licenses', 'Licenses'),
            ('Organizational Costs', 'Organizational Costs'),
            ('Other Long-term Assets', 'Other Long-term Assets'),
            ('Other intangible assets', 'Other intangible assets'),
            ('Prepayments and accrued income', 'Prepayments and accrued income'),
            ('Security Deposits', 'Security Deposits'),
        ],
        'Accounts Payable (A/P)': [
            ('Accounts Payable', 'Accounts Payable'),
        ],
        'Credit Card': [
            ('Credit Card', 'Credit Card'),
        ],
        'Other Current Liabilities': [
            ('Current Liabilities', 'Current Liabilities'),
            ('Current Tax Liability', 'Current Tax Liability'),
            ('Current portion of employee benefits obligations', 'Current portion of employee benefits obligations'),
            ('Current portion of obligation under finance leases', 'Current portion of obligation under finance leases'),
            ('Insurance Payable', 'Insurance Payable'),
            ('Interest Payables', 'Interest Payables'),
            ('Line of Credit', 'Line of Credit'),
            ('Loan Payable', 'Loan Payable'),
            ('Payroll Clearing', 'Payroll Clearing'),
            ('Payroll liabilities', 'Payroll liabilities'),
            ('Prepaid Expenses Payable', 'Prepaid Expenses Payable'),
            ('Provision for warranty obligations', 'Provision for warranty obligations'),
            ('Rents in trust – Liability', 'Rents in trust – Liability'),
            ('Short term borrowings from related parties', 'Short term borrowings from related parties'),
            ('Trust Accounts – Liabilities', 'Trust Accounts – Liabilities'),
        ],
        'Long Term Liabilities': [
            ('Accruals and Deferred Income', 'Accruals and Deferred Income'),
            ('Bank loans', 'Bank loans'),
            ('Long term borrowings', 'Long term borrowings'),
            ('Long term employee benefit obligations', 'Long term employee benefit obligations'),
            ('Other Long-Term Liabilities', 'Other Long-Term Liabilities'),
            ('Shareholder Notes Payable', 'Shareholder Notes Payable'),
        ],
        'Equity': [
            ('Accumulated adjustment', 'Accumulated adjustment'),
            ('Common Stock', 'Common Stock'),
            ('Owner\'s Equity', 'Owner\'s Equity'),
            ('Paid-in capital or surplus', 'Paid-in capital or surplus'),
            ('Partner Contributions', 'Partner Contributions'),
            ('Partner Distributions', 'Partner Distributions'),
            ('Partner\'s Equity', 'Partner\'s Equity'),
            ('Preferred Stock', 'Preferred Stock'),
            ('Retained Earnings', 'Retained Earnings'),
            ('Share capital', 'Share capital'),
            ('Treasury Shares', 'Treasury Shares'),
        ],
        'Income': [
            ('Discounts/Refunds given', 'Discounts/Refunds given'),
            ('Non-Profit Income', 'Non-Profit Income'),
            ('Other Primary Income', 'Other Primary Income'),
            ('Sales of Product Income', 'Sales of Product Income'),
            ('Service/Fee Income', 'Service/Fee Income'),
            ('Unapplied Cash Payment income', 'Unapplied Cash Payment income'),
        ],
        'Other Income': [
            ('Dividend Income', 'Dividend Income'),
            ('Gain/loss on sale of fixed assets', 'Gain/loss on sale of fixed assets'),
            ('Gain/loss on sale of investments', 'Gain/loss on sale of investments'),
            ('Income', 'Income'),
            ('Interest earned', 'Interest earned'),
            ('Other Investment Income', 'Other Investment Income'),
            ('Tax-Exempt Interest', 'Tax-Exempt Interest'),
        ],
        'Cost of Goods Sold': [
            ('Cost of Goods Sold', 'Cost of Goods Sold'),
            ('Cost of Labor - COS', 'Cost of Labor - COS'),
            ('Equipment rental - COS', 'Equipment rental - COS'),
            ('Other costs of service - COS', 'Other costs of service - COS'),
            ('Shipping, Freight and Delivery – COS', 'Shipping, Freight and Delivery – COS'),
            ('Supplies and materials - COS', 'Supplies and materials - COS'),
        ],
        'Expenses': [
            ('Advertising/Promotional', 'Advertising/Promotional'),
            ('Auto', 'Auto'),
            ('Bad debts', 'Bad debts'),
            ('Bank charges', 'Bank charges'),
            ('Charitable Contributions', 'Charitable Contributions'),
            ('Cost of Labor', 'Cost of Labor'),
            ('Distribution costs', 'Distribution costs'),
            ('Dues and Subscriptions', 'Dues and Subscriptions'),
            ('Entertainment', 'Entertainment'),
            ('Equipment rental', 'Equipment rental'),
            ('Insurance', 'Insurance'),
            ('Interest paid', 'Interest paid'),
            ('Legal and professional fees', 'Legal and professional fees'),
            ('Meals and entertainment', 'Meals and entertainment'),
            ('Office/General Administrative Expenses', 'Office/General Administrative Expenses'),
            ('Other miscellaneous Service Cost', 'Other miscellaneous Service Cost'),
            ('Payroll Expenses', 'Payroll Expenses'),
            ('Promotional Meals', 'Promotional Meals'),
            ('Rent or lease of Buildings', 'Rent or lease of Buildings'),
            ('Repair and maintenance', 'Repair and maintenance'),
            ('Shipping, Freight and Delivery', 'Shipping, Freight and Delivery'),
            ('Supplies', 'Supplies'),
            ('Taxes paid', 'Taxes paid'),
            ('Travel', 'Travel'),
            ('Travel meals', 'Travel meals'),
            ('Unapplied Cash Bill Payment Expenses', 'Unapplied Cash Bill Payment Expenses'),
            ('Utilities', 'Utilities'),
        ],
        'Other Expenses': [
            ('Amortization', 'Amortization'),
            ('Depreciation', 'Depreciation'),
            ('Exchange Gain or Loss', 'Exchange Gain or Loss'),
            ('Other Miscellaneous Expenses', 'Other Miscellaneous Expenses'),
            ('Penalties and settlements', 'Penalties and settlements'),
        ],
    }

    account_type = models.CharField(max_length=50, choices=ACCOUNT_TYPES)
    detail_type = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    balance = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.name} - {self.detail_type}"
