# Generated by Django 5.0.7 on 2024-07-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='store',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
