# Generated by Django 5.0.7 on 2024-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0004_journalentrylines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentrylines',
            options={'verbose_name_plural': 'Journal Entry Lines'},
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
