# Generated by Django 5.0.7 on 2024-07-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0005_alter_journalentrylines_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentrylines',
            options={},
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='journalentrylines',
            name='description',
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='name_selection_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('vendor', 'Vendor'), ('customer', 'Customer')], default='employee', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='posted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.project'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_lines', to='Journal_Entries.journalentries'),
        ),
    ]
