# Generated by Django 5.0.7 on 2024-07-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COA', '0004_coa'),
        ('Journal_Entries', '0006_alter_journalentrylines_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentrylines',
            options={'verbose_name_plural': 'Journal Entry Lines'},
        ),
        migrations.RemoveField(
            model_name='journalentrylines',
            name='name_selection_id',
        ),
        migrations.RemoveField(
            model_name='journalentrylines',
            name='name_selection_type',
        ),
        migrations.AddField(
            model_name='journalentries',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.customer'),
        ),
        migrations.AddField(
            model_name='journalentries',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.employee'),
        ),
        migrations.AddField(
            model_name='journalentries',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.vendor'),
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='description',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Journal_Entries.project'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='COA.coa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.journalentries'),
        ),
    ]
