# Generated by Django 5.0.7 on 2024-07-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0010_journalentries_journalentrylines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentries',
            name='description',
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
