# Generated by Django 5.0.7 on 2024-07-17 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0012_alter_journalentrylines_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylines',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_lines', to='Journal_Entries.customer'),
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_lines', to='Journal_Entries.employee'),
        ),
        migrations.AddField(
            model_name='journalentrylines',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_lines', to='Journal_Entries.vendor'),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journalentrylines',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal_Entries.journalentries'),
        ),
    ]
