# Generated by Django 5.0.7 on 2024-07-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_forms', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'store')},
        ),
    ]
