# Generated by Django 5.0.7 on 2024-07-18 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoiceentry_grand_total_taxed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
