# Generated by Django 5.0.7 on 2024-07-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_Entries', '0021_customer_store_vendor_store'),
        ('invoice', '0004_alter_invoiceentry_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Journal_Entries.customer'),
        ),
        migrations.AlterField(
            model_name='invoiceentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Journal_Entries.project'),
        ),
        migrations.AlterField(
            model_name='invoiceentrylineproduct',
            name='invoice_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_products', to='invoice.invoiceentry'),
        ),
        migrations.DeleteModel(
            name='InvoiceEntryLineService',
        ),
    ]
