# Generated by Django 5.0.7 on 2024-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoiceentrylineproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentrylineproduct',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
