# Generated by Django 5.0.7 on 2024-07-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoiceentrylineproduct_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partially-Paid', 'Partially-Paid')], default='Pending', max_length=20),
        ),
    ]
